### ISSUE TITLE
docker image for the latest ruby release

### ISSUE THREAD

**Issue by stoivo** [CircleCI-Public/cimg-ruby#111] opened 2023-02-10 10:25 UTC
It would be nice if there existes imaged like `cimg/ruby:3` which would give me the most recent ruby image withing major release. Maybe there should exist `cimg/ruby:lastest` this is just the latest release.

And if you want to be super cool a nighlty release of master of ruby would be cool like `cimg/ruby:master` or `dev` or `nightly`

**Comment by BytesGuy** [comment] 2023-03-26 21:44
@stoivo Hi thanks for the suggestions!

Right now we have no plans to introduce a latest tag for any Docker Convenience Images and this is by design. 

We do this to ensure that jobs based on our images are more deterministic in nature, with minimal changes due to us pushing new tags that switch current to a new major version for example. 

This helps minimise the risk of breaking changes occurring when customers have not explicitly updated their configurations. 

We provide tags for `major.minor` versions which point to the latest patch releases as these are generally compatible and do not cause breaking changes.

The idea for a nightly build is interesting, but we will have to consider whether the points above would also apply :)

I hope this explanation helps and thanks for the suggestions! I will close this issue out, but please feel free to re-open it with any additional comments.

**Closed by BytesGuy** 2023-03-26 21:44 UTC

**Comment by stoivo** [comment] 2023-03-26 22:53
For gems, I like to test for the next release just to make make sure my gem would work with latest version of ruby. This job is allowed fail.

**Comment by BytesGuy** [comment] 2023-03-27 20:11
@stoivo As we don't release alpha/beta/rc versions of upcoming releases, I think your best option here is to create a custom image based on our own Dockerfile template. This would allow you to test on preview versions ahead of time. In this instance as Ruby is simply downloaded and compiled, you just need to pass the correct url into here:

https://github.com/CircleCI-Public/cimg-ruby/blob/99b59659e37e2b06d91521b61d13f945b11f4ee8/Dockerfile.template#L55

I hope this helps!
